blank_issues_enabled: true
contact_links:
  - name: ğŸ’¬ Questions & Discussions ğŸ’¬
    url: https://github.com/Efeckc17/simple-todo-c/discussions
    about: "ğŸ¤ Have a question or want to chat? Join our friendly community discussions!"

